import { createHash } from "node:crypto";
import { readdir, readFile } from "node:fs/promises";
import { resolve } from "node:path";
import type { DatasetVersion, Experiment, Question } from "@pico/lab/contracts";

// Registers the supplied research materials; never makes model calls or starts runs.
const [labId, questionId] = process.argv.slice(2);
if (!labId || !questionId)
  throw new Error(
    "Usage: bun scripts/prepare-multimodal-pilot.ts <lab-id> <question-id>",
  );
const origin = `http://127.0.0.1:${process.env.PICO_PORT ?? "4317"}`;
const prefix = `/api/labs/${encodeURIComponent(labId)}`;
const example = resolve(import.meta.dir, "../examples/multimodal-defense");
const protocol = await readFile(resolve(example, "protocol.md"), "utf8");
const codePaths = ["main.py", "launcher.mjs", "package.json", "bun.lock"];
const templates = await Promise.all(
  ["baseline", "defense"].map(async (arm) => ({
    arm,
    config: JSON.parse(
      await readFile(resolve(example, `config.${arm}.json`), "utf8"),
    ),
  })),
);
const codeFiles = await Promise.all(
  codePaths.map(async (path) => ({
    path,
    content: await readFile(resolve(example, path), "utf8"),
  })),
);

async function request<T>(
  path: string,
  body?: unknown,
  method = "POST",
): Promise<T> {
  const content = body === undefined ? undefined : JSON.stringify(body);
  const response = await fetch(`${origin}${prefix}${path}`, {
    method: content === undefined ? "GET" : method,
    ...(content === undefined
      ? {}
      : {
          headers: {
            "Content-Type": "application/json",
            "Idempotency-Key": `pilot:${createHash("sha256").update(`${questionId}:${path}:${content}`).digest("hex")}`,
          },
          body: content,
        }),
  });
  if (!response.ok)
    throw new Error(
      `Pilot setup failed (${response.status}): ${await response.text()}`,
    );
  return response.json() as Promise<T>;
}

const overview = await request<{ questions: Question[] }>("/overview");
if (!overview.questions.some((question) => question.id === questionId))
  throw new Error("The question must already belong to this laboratory.");

const datasetPaths = (await readdir(resolve(example, "dataset"))).sort();
const files = await Promise.all(
  datasetPaths.map(async (path) => ({
    path,
    content: (await readFile(resolve(example, "dataset", path))).toString(
      "base64",
    ),
    encoding: "base64" as const,
  })),
);
const dataset = await request<DatasetVersion>("/datasets", {
  name: "Harmless visual instruction pilot",
  version: "1",
  source:
    "Synthetic RGB images generated by examples/multimodal-defense/prepare_dataset.py",
  description:
    "Four preserved images: red/blue rectangles, two clean controls and two with the harmless instruction SAY PICO_OVERRIDE. A workflow pilot, not a benchmark.",
  license: "Original synthetic research stimuli; free to reuse.",
  splits: { legitimate: 2, attack: 2 },
  files,
});
const runRequests = templates.map(({ arm, config }) => ({
  arm,
  config: { ...config, dataset_version_id: dataset.id },
  timeoutSeconds: 360,
}));
for (const request of runRequests) {
  codeFiles.push({
    path: `config.${request.arm}.json`,
    content: `${JSON.stringify(request.config, null, 2)}\n`,
  });
}
const experiment = await request<Experiment>("/experiments", {
  title: "Visual instruction defense — four-example pilot",
  objective:
    "Compare baseline and instruction defense on the same target and images, preserving legitimate color identification.",
  questionIds: [questionId],
  datasetVersionIds: [dataset.id],
  protocol,
  entrypoint: "main.py",
  runtime: "python",
  status: "draft",
});
for (const file of codeFiles) {
  await request(`/experiments/${experiment.id}/file`, file, "PUT");
}
await request(
  `/experiments/${experiment.id}`,
  {
    status: "ready",
    reason: "Pilot source and locked dependencies registered before execution.",
  },
  "PATCH",
);
console.log(
  JSON.stringify(
    {
      labId,
      questionId,
      datasetId: dataset.id,
      experimentId: experiment.id,
      files: codeFiles.map((file) => file.path),
      runRequests: runRequests.map(({ arm, ...request }) => ({ arm, request })),
    },
    null,
    2,
  ),
);
